"""
tools/build_trace_viewer.py
=============================
Takes a trace JSON file produced by `python main.py --record-trace ...`
(see simulation/trace_recorder.py) and generates a single self-contained
HTML file that replays the run visually in any browser - no server, no
pygame, no Flask, no internet connection required. Just double-click the
output .html file.

This exists so you can *see* what Phase 1 (and later phases) actually did,
even on a machine where pygame won't install. It is a debugging/inspection
tool, separate from the live Pygame GUI and Flask dashboard that arrive in
later phases - those show a *running* simulation; this replays a
*recorded* one.

Usage:
    python main.py --record-trace data/results/trace.json --robots 3 --ticks 400
    python tools/build_trace_viewer.py data/results/trace.json data/results/trace_viewer.html
"""

from __future__ import annotations

import json
import sys

CELL_COLORS = {
    "EMPTY": "#f4f4f6",
    "WALL": "#2b2f38",
    "SHELF": "#8a5a2b",
    "PICKUP": "#2e9e5b",
    "DROPOFF": "#2b6fce",
    "CHARGING_STATION": "#e0b400",
    "INTERSECTION": "#efe3ff",
}

STATUS_COLORS = {
    "IDLE": "#9aa0a6",
    "MOVING": "#2e9e5b",
    "WAITING": "#e0a300",
    "NEGOTIATING": "#c77dff",
    "REROUTING": "#ff8c42",
    "BLOCKED": "#d1483c",
    "CHARGING": "#e0b400",
    "COMPLETED": "#5b6472",
    "FAILED": "#000000",
}

ROBOT_PALETTE = ["#e63946", "#1d3557", "#2a9d8f", "#f4a261", "#6a4c93",
                  "#457b9d", "#ff006e", "#43aa8b"]

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Decentralized AMR - Trace Viewer</title>
<style>
  :root { color-scheme: light dark; }
  body {
    font-family: -apple-system, Segoe UI, Roboto, sans-serif;
    background: #14161a; color: #e8e8ea; margin: 0; padding: 20px;
  }
  h1 { font-size: 18px; margin: 0 0 4px 0; }
  .sub { color: #9aa0a6; font-size: 13px; margin-bottom: 16px; }
  .layout { display: flex; gap: 20px; flex-wrap: wrap; align-items: flex-start; }
  canvas { background: #1f2229; border-radius: 8px; border: 1px solid #333844; }
  .panel {
    background: #1c1f26; border-radius: 8px; padding: 14px 16px;
    min-width: 300px; border: 1px solid #333844;
  }
  .controls { display: flex; align-items: center; gap: 10px; margin: 14px 0; flex-wrap: wrap; }
  button {
    background: #2e5cff; color: white; border: none; border-radius: 6px;
    padding: 8px 16px; font-size: 14px; cursor: pointer;
  }
  button:hover { background: #4a72ff; }
  input[type=range] { flex: 1; min-width: 200px; }
  select { background: #262a33; color: #e8e8ea; border: 1px solid #3a3f4b; border-radius: 6px; padding: 6px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th, td { text-align: left; padding: 4px 6px; border-bottom: 1px solid #2a2e37; }
  th { color: #9aa0a6; font-weight: 600; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 11px; color: #14161a; font-weight: 600; }
  .frame-info { font-size: 13px; color: #9aa0a6; margin-bottom: 6px; }
  .legend { display: flex; flex-wrap: wrap; gap: 10px; font-size: 12px; margin-top: 10px; color: #9aa0a6; }
  .legend span { display: inline-flex; align-items: center; gap: 5px; }
  .swatch { width: 10px; height: 10px; border-radius: 2px; display: inline-block; }
</style>
</head>
<body>
  <h1>Decentralized AMR &mdash; Trace Viewer</h1>
  <div class="sub">Offline playback of a recorded simulation run. Generated by tools/build_trace_viewer.py</div>

  <div class="layout">
    <div>
      <canvas id="canvas"></canvas>
      <div class="controls">
        <button id="playBtn">Play</button>
        <input type="range" id="scrubber" min="0" max="0" value="0">
        <select id="speed">
          <option value="400">0.5x</option>
          <option value="200" selected>1x</option>
          <option value="100">2x</option>
          <option value="50">4x</option>
          <option value="25">8x</option>
        </select>
      </div>
      <div class="legend" id="legend"></div>
    </div>

    <div class="panel">
      <div class="frame-info" id="frameInfo">tick 0</div>
      <table>
        <thead>
          <tr><th>Robot</th><th>Pos</th><th>Status</th><th>Battery</th><th>Dist</th></tr>
        </thead>
        <tbody id="robotTable"></tbody>
      </table>
    </div>
  </div>

<script>
const TRACE = __TRACE_JSON__;
const CELL_COLORS = __CELL_COLORS_JSON__;
const STATUS_COLORS = __STATUS_COLORS_JSON__;
const ROBOT_PALETTE = __ROBOT_PALETTE_JSON__;

const warehouse = TRACE.warehouse;
const frames = TRACE.frames;
const CELL = 28;
const canvas = document.getElementById('canvas');
canvas.width = warehouse.width * CELL;
canvas.height = warehouse.height * CELL;
const ctx = canvas.getContext('2d');

const robotIds = Object.keys(frames.length ? frames[0].robots : {});
const robotColor = {};
robotIds.forEach((rid, i) => robotColor[rid] = ROBOT_PALETTE[i % ROBOT_PALETTE.length]);

function cellTypeAt(x, y) {
  const key = x + "," + y;
  return warehouse.cells[key] || "EMPTY";
}

function drawWarehouse() {
  for (let y = 0; y < warehouse.height; y++) {
    for (let x = 0; x < warehouse.width; x++) {
      const t = cellTypeAt(x, y);
      ctx.fillStyle = CELL_COLORS[t] || CELL_COLORS.EMPTY;
      ctx.fillRect(x * CELL, y * CELL, CELL, CELL);
      ctx.strokeStyle = 'rgba(0,0,0,0.06)';
      ctx.strokeRect(x * CELL, y * CELL, CELL, CELL);
    }
  }
}

function drawBlockedAisles(frame) {
  ctx.fillStyle = 'rgba(220,60,50,0.45)';
  (frame.blocked_aisles || []).forEach(([x, y]) => {
    ctx.fillRect(x * CELL, y * CELL, CELL, CELL);
  });
}

function drawRobots(frame) {
  Object.entries(frame.robots).forEach(([rid, r]) => {
    const [x, y] = r.position;
    const cx = x * CELL + CELL / 2;
    const cy = y * CELL + CELL / 2;

    ctx.beginPath();
    ctx.arc(cx, cy, CELL * 0.38, 0, Math.PI * 2);
    ctx.fillStyle = robotColor[rid];
    ctx.fill();
    ctx.lineWidth = 2;
    ctx.strokeStyle = STATUS_COLORS[r.status] || '#fff';
    ctx.stroke();

    ctx.fillStyle = '#fff';
    ctx.font = 'bold 11px sans-serif';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText(rid, cx, cy);
  });
}

function renderFrame(idx) {
  if (!frames.length) return;
  const frame = frames[Math.max(0, Math.min(idx, frames.length - 1))];
  drawWarehouse();
  drawBlockedAisles(frame);
  drawRobots(frame);

  document.getElementById('frameInfo').textContent =
    `tick ${frame.tick}  |  sim_time ${frame.sim_time}s  |  frame ${idx + 1}/${frames.length}`;

  const tbody = document.getElementById('robotTable');
  tbody.innerHTML = '';
  Object.entries(frame.robots).forEach(([rid, r]) => {
    const tr = document.createElement('tr');
    const statusColor = STATUS_COLORS[r.status] || '#888';
    tr.innerHTML = `
      <td>${rid}</td>
      <td>(${r.position[0]}, ${r.position[1]})</td>
      <td><span class="badge" style="background:${statusColor}">${r.status}</span></td>
      <td>${r.battery}%</td>
      <td>${r.distance_travelled}</td>`;
    tbody.appendChild(tr);
  });
}

function buildLegend() {
  const legend = document.getElementById('legend');
  const items = [
    ['Wall', CELL_COLORS.WALL], ['Shelf', CELL_COLORS.SHELF],
    ['Pickup', CELL_COLORS.PICKUP], ['Dropoff', CELL_COLORS.DROPOFF],
    ['Charger', CELL_COLORS.CHARGING_STATION], ['Intersection', CELL_COLORS.INTERSECTION],
    ['Blocked aisle', 'rgba(220,60,50,0.7)'],
  ];
  items.forEach(([label, color]) => {
    const span = document.createElement('span');
    span.innerHTML = `<span class="swatch" style="background:${color}"></span>${label}`;
    legend.appendChild(span);
  });
}

let currentFrame = 0;
let playing = false;
let timer = null;

const scrubber = document.getElementById('scrubber');
scrubber.max = Math.max(0, frames.length - 1);
scrubber.addEventListener('input', () => {
  currentFrame = parseInt(scrubber.value, 10);
  renderFrame(currentFrame);
});

const playBtn = document.getElementById('playBtn');
const speedSelect = document.getElementById('speed');

function tick() {
  currentFrame += 1;
  if (currentFrame >= frames.length) {
    currentFrame = frames.length - 1;
    pause();
    return;
  }
  scrubber.value = currentFrame;
  renderFrame(currentFrame);
}

function play() {
  playing = true;
  playBtn.textContent = 'Pause';
  timer = setInterval(tick, parseInt(speedSelect.value, 10));
}
function pause() {
  playing = false;
  playBtn.textContent = 'Play';
  if (timer) clearInterval(timer);
}
playBtn.addEventListener('click', () => (playing ? pause() : play()));
speedSelect.addEventListener('change', () => { if (playing) { pause(); play(); } });

buildLegend();
renderFrame(0);
</script>
</body>
</html>
"""


def build_viewer(trace_path: str, output_path: str) -> None:
    with open(trace_path, "r", encoding="utf-8") as f:
        trace = json.load(f)

    html = HTML_TEMPLATE
    html = html.replace("__TRACE_JSON__", json.dumps(trace))
    html = html.replace("__CELL_COLORS_JSON__", json.dumps(CELL_COLORS))
    html = html.replace("__STATUS_COLORS_JSON__", json.dumps(STATUS_COLORS))
    html = html.replace("__ROBOT_PALETTE_JSON__", json.dumps(ROBOT_PALETTE))

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"Wrote trace viewer to {output_path} "
          f"({len(trace.get('frames', []))} frames). Open it directly in any browser.")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python tools/build_trace_viewer.py <trace.json> <output.html>")
        sys.exit(1)
    build_viewer(sys.argv[1], sys.argv[2])
